package com.feisystems.icas.infrastructure;

public interface MailSenderService {

	public EmailServiceTokenModel sendVerificationEmail(EmailServiceTokenModel emailServiceTokenModel);

	public EmailServiceTokenModel sendRegistrationEmail(EmailServiceTokenModel emailServiceTokenModel);

	public EmailServiceTokenModel sendLostPasswordEmail(EmailServiceTokenModel emailServiceTokenModel);

	public EmailServiceTokenModel sendLostPasswordAndSecurityQuestionsEmail(final EmailServiceTokenModel emailServiceTokenModel);

}
